name: Release
# Release only happens from branch main.
# The current SNAPSHOT version is upgraded to full version.
# If you need to skip to a next minor or major release,
# use versions plugin to create a new SNAPSHOT of that version
# and commit it via a PR like normal.
# Action here:
# 1. prepare release, i.e. create release commit and next version commit.
# 2. release, i.e. sign package and publish to Maven Central.
# 3. release, site
# 4. Do sonar qube analysis, same which is done for PRs.
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    env:
      MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
      GPG_SIGNING_KEY_ID: ${{ secrets.GPG_SIGNING_KEY_ID }}
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: 'main'
          fetch-depth: 0
          fetch-tags: true
          lfs: true
      - id: import-gpg-key
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
          # Make Git config changes global. Need during site publish to GitHub.
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: 'central'
          server-username: 'MAVEN_USERNAME'
          server-password: 'MAVEN_PASSWORD'
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: 'MAVEN_GPG_PASSPHRASE'
      - id: amend-git-config
        name: Amend Git Config
        shell: bash
        # This necessary because of error during site publish (scm-publish to gh-pages):
        # Failed to add new files to SCM: The git-add command failed.
        #   fatal: CRLF would be replaced by LF in fonts/glyphicons-halflings-regular.svg
        run: |
          git config --global core.autocrlf false
          git config --global core.safecrlf false
          git config --global url.https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/.insteadOf https://github.com/
      - id: release-prepare
        name: Create And Commit Release Commits
        shell: bash
        # Leave behind the release.properties file
        run: |
          mvn -X --batch-mode release:prepare
      - id: release-perform
        name: Publish Jar And Site
        shell: bash
        # Deletes the release.properties file if successful release
        run: |
          mvn --batch-mode                                                     \
            --activate-profiles publish                                        \
            --define goals='deploy,site,site:stage,scm-publish:publish-scm'    \
            release:perform
